## 🧾 **Notes: Understanding Why Postfix Sent Old Emails**

**Date:** October 7, 2025
**System:** `pubweb3`
**Mail ID:** `485019600AB`

---

### 🔍 1. What Happened

* Postfix sent an old email today that was originally queued **60 days ago**.
* The log showed:

  ```
  warning: message has been queued for 60 days
  status=sent (250 2.0.0 Ok: queued as 2EBB06C00E9)
  ```
* The **delay value (≈ 5261389 seconds)** confirmed the message had been deferred for around **60 days**.

---

### 🧠 2. Why It Happened

* The message was originally generated by a local web service (`uid=48`, likely Apache or PHP).
* Delivery failed repeatedly with:

  ```
  status=deferred (connect to ALT2.ASPMX.L.GOOGLE.COM[172.217.78.26]:25: Connection timed out)
  ```
* Postfix was attempting to send mail via **Google’s MX servers**, not the internal mail relay.
* This continued for 60 days until the internal mail server (`mx.instem.res.in`) became reachable or properly configured.
* Once reachable, Postfix successfully delivered the pending email.

---

### ⚙️ 3. Key Learnings About Postfix Behavior

* **Deferred mails** remain in the Postfix queue until successfully delivered or expired.
* The **`maximal_queue_lifetime`** parameter defines how long Postfix retries (default: 5 days, in this case: 60 days).
* If the relay or DNS configuration is wrong, emails remain stuck until corrected.
* When the relay becomes available again, Postfix automatically flushes and delivers them.

---

### 🧰 4. Commands Used

| Purpose                 | Command                               |
| ----------------------- | ------------------------------------- |
| Check specific mail log | `grep 485019600AB /var/log/maillog`   |
| View mail queue         | `postqueue -p` or `mailq`             |
| Flush mail queue        | `postqueue -f`                        |
| Check relayhost setting | `grep relayhost /etc/postfix/main.cf` |
| Change Postfix settings | `postconf -e "key = value"`           |
| Reload Postfix          | `systemctl reload postfix`            |

---

### 🧱 5. Fix Implemented / Recommended

1. **Set correct relay host**

   ```bash
   relayhost = [mx.test.res.in]:25
   ```
2. **Reduce retry duration**

   ```bash
   maximal_queue_lifetime = 5d
   bounce_queue_lifetime = 5d
   ```
3. **Flush any remaining queued mails**

   ```bash
   postqueue -f
   ```
4. **Verify mail relay connectivity**

   ```bash
   telnet mx.test.res.in 25
   ```

---

### ✅ 6. Summary

* The “old” email was not resent — it was **finally delivered** after being stuck for two months.
* The root cause was an **incorrect or unreachable relay configuration** that forced Postfix to attempt sending via Google MX, which timed out.
* Once the relay became reachable, Postfix delivered all pending messages.
* Proper configuration and shorter retry limits will prevent such incidents in the future.
